language: java
jdk:
   - oraclejdk8
addons:
   postgresql: "9.4"
sudo: required
services:
   - postgresql
before_install:
   - chmod +x mvnw
   - psql -c "CREATE DATABASE testing_db;" -U postgres
branches:
   only:
   - test
before_script:
   - cp src/main/resources/travis_application.properties src/main/resources/application.properties
deploy:
 provider: heroku
 api-key: f052109c-a2b2-4275-a890-174d86ec8406
  secure: $HEROKU_API_KEY
 app: e1601108reactspring